language: node_js

before_install:
  - npm install -g npm@5.6.0

script: npm run build

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $githubtoken
  on:
    branch: master
  local_dir: dist
  fqdn: housewarming.poiters.be
